invariant-labs/webapp-azero

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Swap/Swap.tsx, src/containers/EventHandlers/market.ts, src/containers/WrappedSwap/WrappedSwap.tsx, src/store/consts/utils.ts, src/store/sagas/pools.ts, src/store/sagas/wallet.ts
tokens for testing:
1 with full data: 5CbrrfFwc9rcJQ4aFrYR79JBDGkEo155ff2cDGnYTGR34ZZZ
2 with address and decimals only: 5E7ujjisb1LLLA3D3RPNdimE5hfoSCXrhzu4uh3AwmCkyuzK
=> handle adding custom tokens

src/components/Swap/Swap.tsx
=> enabled refresh button when wallet is disconnected

src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/NewPosition.tsx, src/store/consts/static.ts
=> add common tokens

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/RangeSelector/style.ts, src/components/NewPosition/style.ts
=> fix view of loader on price range and header on new position page

src/components/PriceRangePlot/PriceRangePlot.tsx
=> fix plot when is no opened positions

src/components/Snackbar/LoadingSnackbar/index.tsx, src/components/Snackbar/LoadingSnackbar/style.ts
=> remove cancel icon from loading snackbar

src/components/Modals/RoutesModal/index.tsx
=> fix regex to match other routes

src/components/PositionDetails/SinglePositionInfo/style.ts
=> fix margin on position details

src/components/Swap/Swap.stories.tsx, src/components/Swap/Swap.tsx, src/store/consts/types.ts, src/store/reducers/swap.ts, src/store/sagas/swap.ts
=> update transaction details in case of insufficient liquidity

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/PoolInit/PoolInit.stories.tsx, src/components/NewPosition/PoolInit/PoolInit.tsx, src/components/NewPosition/PoolInit/style.ts
=> add concentration slider to init pool

src/components/Swap/Swap.tsx
=> change label of transaction details button

src/components/NewPosition/ConcentrationSlider/style.ts, src/components/NewPosition/RangeSelector/style.ts
=> fix concentration slider on mobile

src/store/consts/utils.ts, src/store/selectors/positions.ts
=> prevent throwing an error when token not found for position

src/components/NewPosition/NewPosition.tsx, src/components/NewPosition/PoolInit/PoolInit.tsx, src/store/consts/utils.ts
error appeared because pool was create with edge case mid price equal minimal possible Tick
=> validate mid price for concentration array

src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx
=> sort tokens by balance

src/components/Snackbar/CustomSnackbar/style.ts
=> add shadow for snackbars

src/components/Modals/AddTokenModal/AddTokenModal.tsx, src/components/Modals/AddTokenModal/style.ts, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Modals/SelectModals/style.ts, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/style.ts, src/components/PriceRangePlot/style.ts
=> UI improvements 5 priority

src/components/Modals/SelectModals/style.ts
=> change color of checkbox

src/components/Inputs/Select/Select.tsx, src/components/NewPosition/PoolInit/style.ts, src/components/NewPosition/RangeSelector/RangeSelector.tsx, src/components/NewPosition/RangeSelector/style.ts, src/index.css
- fixed blured background after click back button in browser when modal is opened
- fixed transparent background of buttons, in range selector after click on mobile 
- disabled highlight of after click buttons on mobile
=> Fix blur background and buttons on mobile

src/components/Modals/RoutesModal/index.tsx, src/components/PositionDetails/PositionDetails.tsx, src/components/PositionDetails/SinglePositionInfo/style.ts, src/components/PositionDetails/style.ts
- fix highlight active path (swap) on mobile
- fix market id  and add liquidity position in position details
=> Fix position details layout and select navigation

src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Snackbar/CustomSnackbar/style.ts, src/components/Snackbar/index.tsx, src/containers/Notifier/index.tsx, src/store/consts/static.ts, src/store/reducers/snackbars.ts, src/store/sagas/wallet.ts
- added snackbar in case of insufficient balance of TZERO to make faucet transaction
=> add snackbar to get TZERO

src/components/NewPosition/NewPosition.tsx, src/components/PositionDetails/style.ts, src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Snackbar/CustomSnackbar/style.ts
- fixed layout :
- fixed snackbars on mobile
=> Fix snackbars and layout spacing on mobile

src/components/PositionsList/PositionItem/style.tsx, src/components/PositionsList/PositionsList.tsx, src/components/PriceRangePlot/PriceRangePlot.tsx, src/components/Snackbar/CustomSnackbar/CustomSnackbar.tsx, src/components/Swap/Swap.tsx
- fixed padding in position list item
- fixed a few console errors
=> fix errors and padding

src/components/EmptyPlaceholder/EmptyPlaceholder.tsx, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/PositionsList/PositionsList.stories.tsx, src/components/PositionsList/PositionsList.tsx, src/containers/WrappedPositionsList/WrappedPositionsList.tsx
- fix error message when not provided single token amount 
- change placeholder when no positions found
=> Change placeholder when not found positions

src/components/PositionsList/PositionsList.tsx, src/components/PositionsList/style.ts, src/utils/utils.ts
- fix formatting numbers 
- update layout of position list (mobile)
=> Update position list layout

src/components/NewPosition/NewPosition.tsx, src/components/PositionsList/PositionItem/PositionItem.stories.tsx, src/components/PositionsList/PositionItem/PositionItem.tsx, src/components/PositionsList/PositionsList.stories.tsx, src/containers/NewPositionWrapper/NewPositionWrapper.tsx, src/containers/WrappedPositionsList/WrappedPositionsList.tsx, src/utils/utils.ts
- show token ration in percentage in position list item
- fix 'add liquidity' button
=> Show token ratio in percentage

src/components/Inputs/DepositAmountInput/DepositAmountInput.tsx, src/components/Inputs/DepositAmountInput/style.ts, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/ExchangeAmountInput/style.ts, src/components/NewPosition/MarketIdLabel/style.ts, src/components/NewPosition/RangeSelector/style.ts, src/components/PositionDetails/SinglePositionInfo/BoxInfo.tsx, src/components/PositionDetails/SinglePositionInfo/style.ts, src/components/PositionsList/PositionsList.tsx, src/components/Swap/Swap.tsx, src/components/Swap/TokensInfo/SingleToken/SingleToken.tsx
- add tooltips for token link and estimated balance
- add hover highlight for copy market id
- fix tokens animation on swap
=> Final fixes

package-lock.json, src/components/Swap/Swap.tsx, src/containers/HeaderWrapper/HeaderWrapper.tsx, src/containers/WrappedSwap/WrappedSwap.tsx, src/store/sagas/pools.ts, src/store/sagas/wallet.ts, src/utils/web3/selector.ts
- fix error of balance with custom tokens
- fix reconnect wallet
- fix error of URL without selected tokens in swap
=> fix error of balance and reconnect wallet

package-lock.json, src/App.tsx, src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Inputs/Select/Select.stories.tsx, src/components/Inputs/Select/Select.tsx, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.stories.tsx, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/components/Modals/Slippage/Slippage.stories.tsx, src/components/Modals/Slippage/Slippage.tsx, src/components/Modals/Slippage/style.ts, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/NewPosition/NewPosition.tsx, src/components/PositionDetails/SinglePositionInfo/SinglePositionInfo.tsx, src/components/PositionDetails/SinglePositionInfo/style.ts, src/components/Swap/Swap.tsx, src/containers/WrappedSwap/WrappedSwap.tsx, src/hideErrors.ts, src/store/sagas/swap.ts
- improve slippage modal
- fix hide unknown tokens globally
- improve header in position details
- hide not needed errors from console 
- disabled exchange when swap is not possible
=> Priority 2 improvements

package-lock.json, src/components/NewPosition/DepositSelector/DepositSelector.tsx, src/components/PositionsList/PositionsList.tsx, src/components/Swap/Swap.tsx, src/components/TooltipHover/TooltipHover.tsx, src/components/TooltipHover/style.ts
=> add tooltips

src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx, src/components/Modals/SelectModals/SelectTokenModal/SelectTokenModal.tsx, src/containers/WrappedSwap/WrappedSwap.tsx
- prevent balance loading when wallet is disconnected
=> prevent balance loading when wallet is disconnected

src/components/Inputs/RangeInput/style.ts, src/components/PositionDetails/LiquidationRangeInfo/style.ts, src/utils/utils.ts
=> fix formatting and view for big numbers

src/components/NoConnected/NoConnected.tsx, src/components/NoConnected/style.tsx, src/components/PositionsList/PositionsList.tsx
- new placeholder for position list when wallet is disconnected
=> crate new placeholder for not connected wallet

src/components/NewPosition/PoolInit/PoolInit.tsx, src/components/NewPosition/PoolInit/style.ts, src/components/Swap/ExchangeRate/ExchangeRate.tsx, src/components/Swap/TransactionDetailsBox/TransactionDetailsBox.tsx, src/store/sagas/swap.ts
- fix price impact and Exchange rate
=> fix transation details

src/containers/SinglePositionWrapper/SinglePositionWrapper.tsx, src/containers/WrappedPositionsList/WrappedPositionsList.tsx, src/store/reducers/positions.ts, src/store/sagas/positions.ts
- fix fetch tokens from positions list
reproduction:
- create position with custom token which will be in the middle of your position list
- go to position details of your first position in the list
- clear cache and refresh page
- connect wallet
- go back to the position list
position with custom tokens will not be visible
=> fix fetch tokens from positions list

src/store/sagas/swap.ts
- fix price impact in swap simulation
=> fix price impact in swap simulation
